INSERT INTO RFQ (PARTID, QUANTITY,PARTNAME,  TIMETOSUPPLY, SPECIFICATION) VALUES (1, 275,'Gearbox', 27,'6gears');
INSERT INTO RFQ (PARTID, QUANTITY,PARTNAME,  TIMETOSUPPLY, SPECIFICATION) VALUES (2, 101,'Gearbox', 7,'6gears');
INSERT INTO RFQ (PARTID, QUANTITY,PARTNAME,  TIMETOSUPPLY, SPECIFICATION) VALUES (5, 124,'Chisel Plow', 15,'1000cc');
INSERT INTO RFQ (PARTID, QUANTITY,PARTNAME,  TIMETOSUPPLY, SPECIFICATION) VALUES (8, 302,'Engine', 27,'1000cc');