create database rfq;
use  rfq;
CREATE TABLE `RFQ` (
  `RFQID` int not null auto_increment,
  `PARTID` int(11) NOT NULL,
  `QUANTITY` int(30),
  `PARTNAME` varchar(16) ,
  `TIMETOSUPPLY` int(30) ,
  `SPECIFICATION` varchar(30) ,
  
PRIMARY KEY (`RFQID`)
);

INSERT INTO RFQ (PARTID, QUANTITY,PARTNAME,  TIMETOSUPPLY, SPECIFICATION) VALUES (1, 275,'Gearbox', 27,'6gears');
INSERT INTO RFQ (PARTID, QUANTITY,PARTNAME,  TIMETOSUPPLY, SPECIFICATION) VALUES (2, 101,'Gearbox', 7,'6gears');
INSERT INTO RFQ (PARTID, QUANTITY,PARTNAME,  TIMETOSUPPLY, SPECIFICATION) VALUES (5, 124,'Chisel Plow', 15,'1000cc');
INSERT INTO RFQ (PARTID, QUANTITY,PARTNAME,  TIMETOSUPPLY, SPECIFICATION) VALUES (8, 302,'Engine', 27,'1000cc');

